spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data
#    username: sa
#    password: password
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: 192.168.0.220
    username: admin
    password: nichuja.1990
